#include <cstdio>
#include <cstring>
#include <iostream>
#include <algorithm>
using namespace std;
int n,t,dp[25][25],a[25],tmp[25];
int main() {
    cin>>n;
    for(int i=0;i<n;i++) {
        cin>>t;
        a[t-1]=i;
    }
    while(cin>>t) {
        tmp[t-1]=0;
        for(int i=1;i<n;i++) {
            cin>>t;
            tmp[t-1]=i;
        }
        memset(dp,0,sizeof(dp));
        for(int i=0;i<n;i++) {
            for(int j=0;j<n;j++) {
                if(a[j]==tmp[i]) dp[i+1][j+1]=dp[i][j]+1;
                else dp[i+1][j+1]=max(dp[i][j+1],dp[i+1][j]);
            }
        }
        printf("%d\n",dp[n][n]);
    }
    return 0;
} 